### ISSUE TITLE
Context menu shows double menu entries after a commit

### ISSUE THREAD

**Issue by elpaso** [boundlessgeo/qgis-geogiglight-plugin#16]
I'm not sure that this is a bug or a feature:
![image](https://cloud.githubusercontent.com/assets/142164/16841623/5dba055e-49da-11e6-9e14-2c87a6a70d6b.png)

Is it expected that the menu items are duplicated?

**Comment by elpaso** [comment]
Confirmed as a bug

**Comment by gioman** [comment]
I'm using the latest code revision and I'm seeing this happen a lot, when I don't remember to have the same issue in the previous days.

**Comment by volaya** [comment]
Yes, same here. I suspect it might have something to do with the layer reloads, but now I am not able to consistently reproduce it.... :-(

**Comment by gioman** [comment]
@volaya with the latest code revision of GG Light, doing manual tests in Tester plugin (using GG server RC3 in testing Docker container) is pretty easy to replicate this issue. When this happens the menu entries that must be used to continue are the bottom ones, otherwise using others leads to errors.

**Comment by gioman** [comment]
for some reason this seems to have stopped to be a issue. I'm not seeing this anymore while using the latest revision codes while testing the plugin. Will reopen if necessary,
