### ISSUE TITLE
add "remove layer from repo" and "change to a different version" also in history panel(?)

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-geogiglight-plugin#51]
Frequently when using the GG plugin I kind of naturally looked to

"remove layer from repo"

or 

"change to a different version" 

directly right clicking on a specific version in history panel.

Of course "change to a different version" in this context would become "change to this version".

**Comment by volaya** [comment]
"remove layer" should be easy. "Change to this version" might be more tricky, since there might be several exported layers, and each of them in a different version. And some layers might not be exported at all. But we can show a message to confirm, saying "Do you want to change all exported layers to this version?". Do you think that would be clear enough?

**Comment by volaya** [comment]
Both added. For the 'change to this version' it is available for each separate layer, if the layer is open in the current project. Let me know what you think

**Comment by gioman** [comment]
> Both added. For the 'change to this version' it is available for each separate layer, if the layer is open in the current project. Let me know what you think

brillant!
